import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/sidebar";
import { UseInitPopovers } from "@/app/hooks/useInitPopovers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="flex min-h-screen"> {/* Full-height flex container */}
            <Sidebar />
            <main className="flex-1 ml-64 p-6"> {/* Sidebar width + padding */}
                {children}
            </main>
        </div>
        <UseInitPopovers />
        </body>
        </html>
    );
}
